import { FC, PropsWithChildren } from "react";
import { Inter } from "next/font/google";
import { Header } from "@/components";
import "./globals.css";
import { fontConfig } from "@/theme";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout: FC<PropsWithChildren> = ({ children }) => {
  return (
    <html lang="en">
      <body className={fontConfig.className}>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
};

export default RootLayout;
