import { FC, PropsWithChildren } from "react";
import "./globals.css";
import { fontConfig } from "@/UI-kit/theme";
import StyledComponentsRegistry from "@/app/registry";
import { LayoutMain } from "../screens";

export const metadata = {
  title: "Films",
  description: "Generated by create next app",
};

const RootLayout: FC<PropsWithChildren> = ({ children }) => {
  return (
    <html lang="en">
      <StyledComponentsRegistry>
        <body className={fontConfig.className}>
          <LayoutMain>{children}</LayoutMain>
        </body>
      </StyledComponentsRegistry>
    </html>
  );
};

export default RootLayout;
