import { PaletteConfigType } from "@/UI-kit/theme";

export const paletteDarkConfig: PaletteConfigType = {
  primary: {
    main: "#AC1B1B",
    dark: "#660e0e",
    light: "#ff7171",
    additional: "#606165",
    contrastText: "#fff",
    additionalText: "#2F2F32",
  },
  secondary: {
    main: "#3949AB",
    dark: "#27367f",
    light: "#E8EAF6",
    contrastText: "#fff",
    additional: "#606165",
    additionalText: "#000",
  },
  text: {
    main: "#21252a",
    dark: "#000",
    light: "#6b6b6b",
    contrastText: "#fff",
    additional: "#606165",
    additionalText: "#000",
  },
  background: {
    main: "#100F12",
    dark: "#000",
    light: "#ffffff",
    contrastText: "#fff",
    additional: "#606165",
    additionalText: "#000",
  },
  border: {
    main: "#1C1B1C",
    dark: "#00578e",
    light: "#8ed0ff",
    contrastText: "#fff",
    additional: "#606165",
    additionalText: "#000",
  },
  success: {
    main: "",
    dark: "",
    light: "",
    contrastText: "",
    additional: "#606165",
    additionalText: "#000",
  },
  warning: {
    main: "",
    dark: "",
    light: "",
    contrastText: "",
    additional: "#606165",
    additionalText: "#000",
  },
  error: {
    main: "",
    dark: "",
    light: "",
    contrastText: "",
    additional: "#606165",
    additionalText: "#000",
  },
};
