import { PaletteConfigType } from "@/UI-kit/theme";

export const paletteLightConfig: PaletteConfigType = {
  primary: {
    main: "#3949AB",
    dark: "#27367f",
    light: "#E8EAF6",
    contrastText: "#fff",
    additionalText: "#000",
    additional: "#606165",
    disabled: "#cccccc",
  },
  secondary: {
    main: "#ff9a00",
    dark: "#925600",
    light: "#ffc569",
    contrastText: "#fff",
    additionalText: "#000",
    additional: "#606165",
    disabled: "#cccccc",
  },
  text: {
    main: "#21252a",
    dark: "#000",
    light: "#6b6b6b",
    contrastText: "#fff",
    additionalText: "#000",
    additional: "#606165",
    disabled: "#cccccc",
  },
  background: {
    main: "#ffffff",
    dark: "#ffffff",
    light: "#ffffff",
    contrastText: "#3949AB",
    additionalText: "#000",
    additional: "#606165",
    disabled: "#cccccc",
  },
  border: {
    main: "#7e7e7e",
    dark: "#00578e",
    light: "#8ed0ff",
    contrastText: "#fff",
    additionalText: "#000",
    additional: "#606165",
    disabled: "#cccccc",
  },
  success: {
    main: "",
    dark: "",
    light: "",
    contrastText: "",
    additionalText: "#000",
    additional: "#606165",
    disabled: "#cccccc",
  },
  warning: {
    main: "",
    dark: "",
    light: "",
    contrastText: "",
    additionalText: "#000",
    additional: "#606165",
    disabled: "#cccccc",
  },
  error: {
    main: "",
    dark: "",
    light: "",
    contrastText: "",
    additionalText: "#000",
    additional: "#606165",
    disabled: "#cccccc",
  },
};
